# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cb23c3c7a0182e02718093940caccb2f5d54eab02a816e054f6f33e246e4698256564cecdbebc59b76cc7186f69a08ad7447edadb073ecf307b29a207221451

test:
  secret_key_base: bd07757352766891d398efce871daf383e3cea810282e88cc10a76adde4f85dacd4f4115e881e92c7493e2edcfcf6e85518eff5f3b54fb8e1922fc69f1f2672c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
